# configs/bart.yaml
model:
  name: "facebook/bart-large-cnn"

data:
  dataset_name: "alexfabbri/multi_news"
  max_input_length: 1024
  max_output_length: 142    # match BART‐CNN default
  batch_size: 4
  num_workers: 4
  sample_ratio: 1.0
  remove_stopwords: false
  dedup: True
  dedup_threshold: 0.5


training:
  epochs: 2
  lr: 2e-05
  warmup_steps: 500
  weight_decay: 0.01
  fp16: true
  log_interval: 100
  seed: 42

generation:
  num_beams: 4
  length_penalty: 2.0      # from generation_config.json
  min_length: 5
  no_repeat_ngram_size: 2
  early_stopping: true

output:
  output_dir: "outputs/bart"

ddp:
  backend: "nccl"
  init_method: "env://"
  world_size: 4

evaluation:
  bootstrap_iters: 100
