# configs/base.yaml
model:
  name: "google/pegasus-large"
data:
  dataset_name: "alexfabbri/multi_news"
  max_input_length: 1024
  max_output_length: 256
  batch_size: 4
  num_workers: 4
  sample_ratio: 1.0
  remove_stopwords: false
training:
  epochs: 3
  lr: 3e-05
  warmup_steps: 500
  weight_decay: 0.01
  fp16: false
  log_interval: 100
  seed: 42
generation:
  num_beams: 4
  length_penalty: 1.0
output:
  output_dir: "outputs/pegasus"
ddp:
  backend: "nccl"
  init_method: "env://"
  world_size: 1
