data:
  dataset_name: "alexfabbri/multi_news"
  sample_ratio: 0.02  # Start with 2% of the data
  max_input_length: 4096  # LED can handle longer inputs
  max_output_length: 256
  batch_size: 1  # Smaller batch size due to model size
  num_workers: 4
  seed: 42

model:
  model_name: "allenai/led-base-16384"  # LED model
  learning_rate: 5.0e-5
  weight_decay: 0.01
  warmup_steps: 500
  max_grad_norm: 1.0
  gradient_accumulation_steps: 16  # Increase for larger models

training:
  output_dir: "outputs/led_models"
  num_epochs: 3
  eval_steps: 500
  save_steps: 1000
  logging_steps: 100
  use_fp16: true
  distributed: false
  local_rank: -1
  world_size: 1