# # configs/pegasus.yaml
# model:
#   name: "google/pegasus-large"
# data:
#   dataset_name: "alexfabbri/multi_news"
#   max_input_length: 1024
#   max_output_length: 256
#   batch_size: 4
#   num_workers: 4
#   sample_ratio: 1.0
#   remove_stopwords: false
# training:
#   epochs: 3
#   lr: 3e-05
#   warmup_steps: 500
#   weight_decay: 0.01
#   fp16: false
#   log_interval: 100
#   seed: 42
# generation:
#   num_beams: 4
#   length_penalty: 1.0
# output:
#   output_dir: "outputs/pegasus"
# ddp:
#   backend: "nccl"
#   init_method: "env://"
#   world_size: 1

# configs/pegasus.yaml
model:
  name: "google/pegasus-large"

data:
  dataset_name: "alexfabbri/multi_news"
  max_input_length: 1024
  max_output_length: 256
  batch_size: 2
  num_workers: 4
  sample_ratio: 1.0
  remove_stopwords: false
  dedup: True
  dedup_threshold: 0.5


training:
  epochs: 2
  lr: 1e-05
  warmup_steps: 500
  weight_decay: 0.01
  fp16: true
  log_interval: 100
  seed: 42
  gradient_accumulation_steps: 4
  gradient_checkpointing: true


generation:
  num_beams: 4
  length_penalty: 0.8
  min_length: 5
  no_repeat_ngram_size: 3
  early_stopping: true

output:
  output_dir: "outputs/pegasus"
  # output_dir: "pegasus/tmp"

ddp:
  backend: "nccl"
  init_method: "env://"
  world_size: 4

evaluation:
  bootstrap_iters: 100

